# Generated by Django 5.1 on 2024-11-25 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_searchstatistics_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
    ]
